sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: CL3afLkZmRCL1lCyaC0qzuWLOiGTxJnpd2qwyZ3jAZl14bz+AgcTenTpveYBvC7ysQOLOvbScaQi0mk6gXweBTcy6eHiL5t79yTBz84h2WueLM8zwu6PnqPSR0AOcrLDZh8HS8+SO9eQ6jEC4l2Ut9Z6nVblknKGgUAwcXJln2MmVapp81RFaXwTb0YGLtVd/urGE5+sV4rKM0fHTxvW4kZ4wp+tYxub4YXaoqUMjYJTfR0WBMQMNrteT7hztCt7MyP1j6fAe4rae5rPG+SYWcyyETE+sklQnl8vvzxF1GbRDw0ymdUvZezDrFqPrgDZWFsuECgrLiTKZGfFkexEnnf682TuqIOpHOp7G4TbSBSxOotihUFED/7pjtjP0kD5LRngMHWLHAwjWL2BJwNMdMnWtGwRxkcFptTrmvYZ8Rf3xk0pAnOlfDT+6Fn5tjufukPo+XoVMK/B2Pom3VyRfH13qkZdMfEhDYOSAQweNDaOdG5l5IVnEuBsUnByDR4PE47SStX1I/y1MTkgF/n9heNxZkNDOP1Ua3cMLcf4hqZA/YM/C9R1jEKpKSuNV1YWpqyxLaj/ho0BUEzgeYTLmmYqLfWD7YT423ZhWlfe/PkTmDphuz9wLV6Abc04mVbq1bRGVAYDgxmFgqURgbCNyeAmnoys+vfMXAsWmfITNsE=
  - secure: blc1pFR8NHD/9qSwacSy2G5Wcgbfy6HbnU8AsTlEm3xcicr17E1H8YXhyFZu76TGWXjWhVMk5A3snYkgyNWOE1PyiZptc1Mmdrv3snAPaqWXbLVC3ArGPdtQ7pAmMEqEIwxZRV18bTmol4MnJhmMArAJkeqxSClQJ8r46JAzJKdKFzVBYGq6NujcjOKfNL4JC/AnzDmX19BEwWM2o9cKJzeNkXTu8+0Y4njTUiUy2UbA2sutEctXb5BXkU+kwNIkcFNWv+qzHQTaWmZZRxGBnGiA5ixO+XngJ6mOIry93IfG3TSYRqjbPOzx9vTmC/+7V7vbdc017Dh5ZJJab5JYyBnmLXPsdRLAocZK9/l7bvrl+ZYsUuiqp54FI2fKxpSZXbSuyySMv2EkYMSI1GsTll705Q5/C//gWQx2TNCFrGZIe3rn5lUs4vl3R/WmSCW3sRFG93CDK/kJiBv+XRo4C58Op8tFSQQnirGj9C3jA9Ntbo/+u3/ewAW1ntxKnMvhtZ9/mZrtjIAEpnH2e1qV76JZTDHbKNqSWSYbijc8I2aJ24eQ2UZhUmCPN60OKT1DSnjtXIPzbahPQ5phkNnR+CarCV3rrKETe5YeSEqfJU16GcIYx6IaY1jR/MOEKnIhh4hfIunrRYUz7vhJrMToXNGiE783uHxUk+SFwglnwR8=
